#!/bin/bash

clear
echo -e "================================================="
echo -e "#       This Script Edited By Tareq Agil        #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Build Up By Tareq Agil                        #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Allah SWT                                     #"
echo -e "# My Team                                       #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# samsulvpn                                     #"
echo -e "# Tareq Agil                                    #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
